version: '3.9'
services:
    app:
        container_name: boompow_dev
        ports:
            - '127.0.0.1:8080:8080'
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - $PWD:/app:cached
        restart: on-failure
        entrypoint: /bin/zsh
        stdin_open: true
        tty: true
        networks: ['app-network']

networks:
    app-network:
        driver: bridge